// Generated by delombok at Tue Feb 02 13:58:02 CET 2021
package pw.cinque.keystrokesmod;

import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import cpw.mods.fml.common.gameevent.TickEvent;
import net.minecraft.client.Minecraft;
import pw.cinque.keystrokesmod.gui.GuiKeystrokes;

/**
 * This class draws the keystrokes on the screen when the {@link GuiKeystrokes} screen isn't open.
 */
public class KeystrokesRenderer {
    private final KeystrokesMod keystrokesMod;

    @SubscribeEvent
    public void onRenderTick(TickEvent.RenderTickEvent event) {
        if (Minecraft.getMinecraft().inGameHasFocus) {
            keystrokesMod.getKeyHolder().draw(0, 0);
        }
    }

    @java.lang.SuppressWarnings("all")
    public KeystrokesRenderer(final KeystrokesMod keystrokesMod) {
        this.keystrokesMod = keystrokesMod;
    }
}
