// Generated by delombok at Tue Feb 02 13:58:02 CET 2021
package pw.cinque.keystrokesmod.util;

import org.lwjgl.opengl.GL11;

/**
 * This class contains color-related utility methods for the renderer.
 */
public class ColorUtil {
    /**
     * Sets the current OpenGL color.
     *
     * @param color The ARGB color
     */
    public static void setGlColor(int color) {
        float alpha = (color >> 24 & 255) / 255.0F;
        float red = (color >> 16 & 255) / 255.0F;
        float green = (color >> 8 & 255) / 255.0F;
        float blue = (color & 255) / 255.0F;
        GL11.glColor4f(red, green, blue, alpha);
    }

    @java.lang.SuppressWarnings("all")
    private ColorUtil() {
    }
}
